Adding modulo and inverse modulo caclulator, Resolving issue #99
vasu-1/CalcHub pull request #120
Opened 2022-03-08 06:37 UTC by AnIkeT126

## Description 📜

This PR adds a calculator that aims to calculate the modulus and inverse modulus of two given numbers and is made using HTML, CSS & JS.

Fixes #99 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

![image](https://user-images.githubusercontent.com/82095877/157040325-fcb0e630-583c-4fb2-af0c-4f4936364a27.png)

![image](https://user-images.githubusercontent.com/82095877/157039611-372ff927-6780-4386-93fc-3324135a0ff4.png)

![image](https://user-images.githubusercontent.com/82095877/157040418-b1be4345-f46a-49ae-9def-26f049b9ef00.png)

![image](https://user-images.githubusercontent.com/82095877/157040727-c03e8096-4c0e-4382-8f2e-7da5ad415819.png)

2022-03-08 10:22 UTC, AnIkeT126 commented
@vasu-1 can you review this PR, this is in accordance will all the guidelines and contains the code file along with a readme that contains the screenshots of the output.

2022-03-08 14:48 UTC, mansi-garg-12 approved these changes
Good to go checked!

2022-03-09 03:48 UTC, vasu-1 requested changes

2022-03-09 03:48 UTC, vasu-1 commented on Calculators/Modulo_Inverse_Modulo_Calculator/index.html
> +    <title>Affine Cipher</title>
change title

2022-03-09 03:48 UTC, vasu-1 commented on Calculators/Modulo_Inverse_Modulo_Calculator/readme.md
> +
add only two screenshots !!

2022-03-09 06:32 UTC, AnIkeT126 commented
I have updated the changes in a new PR

2022-03-09 06:32 UTC, closed without merging