Necessary files were added
vasu-1/CalcHub pull request #139
Opened 2022-03-10 04:23 UTC by BinilTomJose1278

## Description 📜

I have created a Love Calculator , and deployed the basic functionalities into it. 
Fixes # <issue_number_here>

<hr>
 
## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2022-03-11 04:57 UTC, BinilTomJose1278 commented
The title of the pull request has been changed.

2022-03-12 20:00 UTC, BinilTomJose1278 commented
Anymore changes to be done?

2022-03-17 18:05 UTC, vasu-1 requested changes
Hey @BinilTomJose1278 
Thanks for your interest in this project !
But is this calculator making any sense ?
I guess , love calculator is not needed !
You can go for another one !!!

2022-03-17 18:05 UTC, vasu-1 submitted a review, later dismissed

2022-03-17 18:06 UTC, closed without merging