Basic Physics Calculator
vasu-1/CalcHub pull request #240
Opened 2022-04-13 06:22 UTC by RiyaJain12

A calculator that calculates the basics physics quantities like speed,acceleration,velocity ,force etc. It also has the functionality that it can give the answer in  any unit we wanted to get.It also has the side navbar for the direct move to the page that has the parameter we wants to find.

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # 236

<hr>
 
## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/.github/CODE_OF_CONDUCT.MD) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GSSOC'22 contributor
- [ ] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸
![Screenshot (180)](https://user-images.githubusercontent.com/90452678/163113093-da35f40c-03d5-4168-a9fa-c9334df44f80.png)

<hr>

2022-04-13 15:11 UTC, mansi-garg-12 requested changes
Code is good to go...
But try to make it more responsive for phone, tablet 
Example size of input box is too small in case of phone and tablet.

2022-05-04 08:34 UTC, vasu-1 requested changes
Make it responsive !!

add this following line in the head tag
`<meta name="viewport" content="width=device-width, initial-scale=1.0" />`

and try to make is responsive !

suggestion :  use bootstrap

2022-05-04 08:34 UTC, vasu-1 commented on Calculators/Basic_physics calculator/styles.css
> +
remove unnecessary lines !!

2022-05-10 02:22 UTC, RiyaJain12 commented
@vasu-1 
done!

2022-05-11 07:31 UTC, vasu-1 requested changes
Remove `.vscode/settings.json` from pr!

And yeah, as shown in below image, that drawer is not visible in mobile screen mode!
can you just fix it ?
![image](https://user-images.githubusercontent.com/76911582/167793680-3ae0aac5-dd37-4256-97cd-1c283d0c6e7e.png)

2022-05-11 07:31 UTC, vasu-1 commented on Calculators/Basic_physics calculator/styles.css
> +
remove these lines too

2022-05-24 05:12 UTC, RiyaJain12 commented
@vasu-1 
done all the changes!

2022-05-28 02:42 UTC, vasu-1 approved these changes
LGTM @RiyaJain12

2022-05-28 02:43 UTC, merged