CaeserCipher Calculator Added
vasu-1/CalcHub pull request #328
Opened 2022-05-21 14:19 UTC by Siddhi-Mundada

## Caeser Cipher Calculator is added.
The Caesar Cipher technique is one of the earliest and simplest method of encryption technique. It’s simply a type of substitution cipher.  
I added 4 files :  1)caesercipher.html (for creating frontend form layout and adding information about the algorithm),
<br>
2) caeser.css(for styling of page and adding padding, margin ,background color) , 
<br>
3)caeser.js (contains the logic for output) 
<br>
4)readme.md(information of algorithm ,working of form ,contains screenshot of work)

 #53 
<hr>
Please review my work. Thanks in Advance!
 <hr>
## Checklist ✅
- [X] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GSSOC'22 contributor
<hr>
## Screenshots 📸
##  Information of Caeser Cipher Algorithm is added with one example Image. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/75447890/169655077-4364969a-f582-4782-84e7-7be196c4cfd4.png">
<hr>
## After giving Input in first row-TEXT and second row(input text) - OFFSET output will appear in third box-FINISH.
<img width="920" alt="image" src="https://user-images.githubusercontent.com/75447890/169655147-737c524e-bef1-4335-9b13-d27495aec068.png">
## Working of Calculator
<img width="834" alt="image" src="https://user-images.githubusercontent.com/75447890/169655220-462ebfc7-66e6-4a53-93a2-81f76cc2822a.png">

2022-05-24 17:08 UTC, mansi-garg-12 approved these changes
good to go...
Ready to merge

2022-05-28 03:28 UTC, vasu-1 requested changes

2022-05-28 03:28 UTC, vasu-1 commented on Calculators/CaeserCipher_Calculator/caesercipher.html
> +  </script> -->
remove this commented code !

2022-05-28 03:29 UTC, vasu-1 commented
Reformat the pull description !

![image](https://user-images.githubusercontent.com/76911582/170808162-e7ba1542-93fc-43ac-a043-643d4837a1bd.png)

2022-05-28 06:23 UTC, closed without merging