Fraction (done changes 👍)
vasu-1/CalcHub pull request #340
Opened 2022-05-25 13:59 UTC by DragonUncaged

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #338 

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/vasu-1/CalcHub/blob/main/.github/ContributingGuidelines.md) & [Code of conduct](https://github.com/vasu-1/CalcHub/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GSSOC'22 contributor
- [x] Have you added a working video of your calculator ?

<hr>

## Screenshots / Gif (Optional) 📸

![image](https://user-images.githubusercontent.com/72241207/170280447-bceb17b5-a898-49f2-b7b3-3e9ceb44327b.png)

2022-05-27 18:30 UTC, mansi-garg-12 requested changes
good
Try to make is responsive.

2022-05-29 23:09 UTC, DragonUncaged commented
> good Try to make is responsive.

![image](https://user-images.githubusercontent.com/72241207/170894955-0be8b110-c89b-4dd9-b661-18c1c638efcb.png)

2022-05-31 17:20 UTC, Chayan-11 approved these changes

2022-06-01 05:33 UTC, vasu-1 approved these changes
LGTM @DragonUncaged

2022-06-01 05:33 UTC, merged